networks:
  custom_network:
    driver: bridge

services:
  django:
    depends_on: mysql
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: mysql
      MYSQL_PORT: $MYSQL_PORT
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    networks:
      - custom_network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: $MYSQL_PORT
    ports:
      - "8080:80"
    networks:
      - custom_network

  android:
    image: amrka/android-emulator:nexus6_playstore-latest
    container_name: android
    restart: always
    tty: true
    environment:
        - DISPLAY=host.docker.internal:0

#    vnc:
#      image: android-emulator
#      build: .
#      ports:
#        - "5900:5900"
#      container_name: vnc
#      environment:
#        VNC_PASSWORD: 123
#        privileged: true
#      command:
#        - bash
#        - -c
#        - |
#          $START_VNC
#      tty: true
#      stdin_open: true
